const app=document.getElementById('app');
const qs=new URLSearchParams(location.search);
const initialRole=qs.get('role');
const savedTeacher=JSON.parse(localStorage.getItem('yisraeliTeacher')||'null');
const voterId=localStorage.getItem('yisraeliVoterId')||crypto.randomUUID();
localStorage.setItem('yisraeliVoterId',voterId);
let state={screen:initialRole==='teacher'?'teacherHome':initialRole==='student'?'studentJoin':'home',room:null,teacherToken:savedTeacher?.teacherToken||'',role:initialRole||'',message:'',poll:null};
const stageNames={1:'ענן הזהות',2:'מפת הזהות הכיתתית',3:'מה הופך לישראלי?'};
const identityIcons={'יהדות':'✡','עברית':'א','מקום':'⌖','משפחה':'♡','קהילה':'◌','תרבות':'♫','זיכרון':'◫','עתיד':'→'};

function e(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function api(method,body,query=''){
 const res=await fetch('/api/room'+query,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});
 const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'request_failed');return data;
}
function setMessage(msg=''){state.message=msg;render()}
function home(){state={...state,screen:'home',room:null,role:'',message:''};render()}
function shell(content){return `<main class="wrap"><section class="hero"><div class="eyebrow">תוכנית השכלה כללית · שכבה י׳</div><h1>אני ישראלי</h1><p>מסע כיתתי חי בעקבות זהות, שייכות ומה שאנחנו בוחרים לקרוא לו ישראליות.</p></section>${content}<div class="footer">מקיף ז׳ אשדוד · פעילות כיתתית חיה</div></main>`}
function message(){return state.message?`<div class="notice">${e(state.message)}</div>`:''}

function renderHome(){app.innerHTML=shell(`<section class="panel"><div class="role-grid"><button class="card" id="teacher"><h3>מסך מורה</h3><p>יצירת מרחב כיתתי, קוד ו־QR, פתיחת התחנות וצפייה בתוצאות.</p></button><button class="card" id="student"><h3>מסך תלמיד</h3><p>הצטרפות לכיתה בקוד אחד והתקדמות דרך שלוש התחנות.</p></button></div></section>`);document.getElementById('teacher').onclick=()=>{state.screen='teacherHome';render()};document.getElementById('student').onclick=()=>{state.screen='studentJoin';render()}}
function renderTeacherHome(){const resume=savedTeacher?.code?`<button class="btn secondary" id="resume">המשך מרחב ${e(savedTeacher.code)}</button>`:'';app.innerHTML=shell(`<section class="panel"><div class="row space"><div><h2>פתיחת שיעור חדש</h2><p class="muted">קוד אחד ישמש את הכיתה בכל שלוש התחנות.</p></div><button class="btn ghost" id="back">חזרה</button></div>${message()}<label>שם הכיתה / הקבוצה</label><input class="input" id="className" placeholder="לדוגמה: י׳3"/><div class="row" style="margin-top:14px"><button class="btn" id="create">צור מרחב כיתתי</button>${resume}</div></section>`);document.getElementById('back').onclick=home;document.getElementById('create').onclick=createRoom;if(document.getElementById('resume'))document.getElementById('resume').onclick=()=>resumeTeacher(savedTeacher)}
async function createRoom(){try{const className=document.getElementById('className').value;const data=await api('POST',{action:'create',className});state.room=data;state.teacherToken=data.teacherToken;state.screen='teacherRoom';localStorage.setItem('yisraeliTeacher',JSON.stringify({code:data.code,teacherToken:data.teacherToken}));render();startPolling()}catch(err){setMessage('לא הצלחתי ליצור מרחב חדש. נסה שוב.')}}
async function resumeTeacher(saved){try{const data=await api('GET',null,`?code=${encodeURIComponent(saved.code)}&teacherToken=${encodeURIComponent(saved.teacherToken)}`);state.room=data;state.teacherToken=saved.teacherToken;state.screen='teacherRoom';render();startPolling()}catch{localStorage.removeItem('yisraeliTeacher');setMessage('המרחב הקודם כבר אינו זמין.')}}

function teacherStageContent(){const r=state.room;if(r.activeStage===1)return teacherCloud(r.summary);if(r.activeStage===2)return teacherIdentity(r.summary);return teacherLab(r.summary)}
function renderTeacherRoom(){const r=state.room;if(!r)return renderTeacherHome();const joinUrl=`${location.origin}/student?code=${r.code}`;app.innerHTML=shell(`<section class="panel"><div class="teacher-top"><div><div class="muted">${e(r.className||'הכיתה שלי')}</div><div class="room-code">${e(r.code)}</div><div class="row"><span class="chip">תחנה ${r.activeStage}: ${e(stageNames[r.activeStage])}</span><span class="chip">${r.stageOpen?'פתוחה לתלמידים':'סגורה'}</span></div></div><img class="qr" alt="QR להצטרפות" src="/api/qr?text=${encodeURIComponent(joinUrl)}"></div><div class="tabs">${[1,2,3].map(s=>`<button class="tab ${r.activeStage===s?'active':''}" data-stage="${s}">${s}. ${stageNames[s]}</button>`).join('')}</div><div class="row"><button class="btn" id="toggle">${r.stageOpen?'סגור תשובות':'פתח לתשובות'}</button><button class="btn secondary" id="visibility">${r.resultsVisible?'הסתר תוצאות מתלמידים':'הצג תוצאות לתלמידים'}</button><button class="btn ghost" id="resetStage">איפוס התחנה</button><button class="btn danger" id="resetAll">איפוס כל השיעור</button></div>${teacherStageContent()}</section>`);document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>teacherAction('setStage',{stage:Number(b.dataset.stage)}));document.getElementById('toggle').onclick=()=>teacherAction('setOpen',{open:!r.stageOpen});document.getElementById('visibility').onclick=()=>teacherAction('setVisibility',{visible:!r.resultsVisible});document.getElementById('resetStage').onclick=()=>teacherAction('resetStage');document.getElementById('resetAll').onclick=()=>{if(confirm('לאפס את כל שלוש התחנות?'))teacherAction('resetAll')}}
async function teacherAction(action,extra={}){try{state.room=await api('POST',{action,code:state.room.code,teacherToken:state.teacherToken,...extra});render()}catch{setMessage('הפעולה לא בוצעה.')}}
function teacherCloud(summary={}){const words=summary?.words||{};const max=Math.max(1,...Object.values(words));const cloud=Object.entries(words).sort((a,b)=>b[1]-a[1]).map(([w,n])=>`<span class="word" style="font-size:${22+Math.round(36*n/max)}px">${e(w)}</span>`).join('');return `<div style="margin-top:20px"><div class="row space"><h2>ישראלי.ת זה...</h2><span class="chip">${summary?.total||0} משתתפים</span></div><div class="cloud">${cloud||'<span class="muted">המילים יופיעו כאן בזמן אמת</span>'}</div></div>`}
function teacherIdentity(summary={}){const avg=summary?.averages||{};return `<div style="margin-top:20px"><div class="row space"><h2>מפת הזהות הכיתתית</h2><span class="chip">${summary?.total||0} משתתפים</span></div><div class="identity-grid">${Object.entries(avg).map(([k,v])=>`<div class="identity-item"><label>${identityIcons[k]||'•'} ${e(k)}</label><div class="room-code" style="font-size:28px;letter-spacing:0">${v||'–'}</div><div class="bar"><span style="width:${(v||0)*20}%"></span></div></div>`).join('')||'<p class="muted">התוצאות יופיעו כאן</p>'}</div></div>`}
function teacherLab(summary={}){return `<div style="margin-top:20px"><div class="row space"><h2>מה הופך לישראלי?</h2><span class="chip">${summary?.total||0} משתתפים</span></div><div class="lab-grid">${(summary?.cases||[]).map(c=>{const total=c.counts.reduce((a,b)=>a+b,0)||1;return `<div class="lab-card"><h3>${e(c.title)}</h3>${c.options.map((o,i)=>`<div style="margin:10px 0"><div class="row space"><span>${e(o)}</span><b>${c.counts[i]||0}</b></div><div class="bar"><span style="width:${((c.counts[i]||0)/total)*100}%"></span></div></div>`).join('')}</div>`}).join('')}</div></div>`}

function renderStudentJoin(){const pre=qs.get('code')||'';app.innerHTML=shell(`<section class="panel"><div class="row space"><div><h2>הצטרפות לשיעור</h2><p class="muted">הכנס את קוד הכיתה שמופיע אצל המורה.</p></div><button class="btn ghost" id="back">חזרה</button></div>${message()}<div class="join"><input class="input" id="code" inputmode="numeric" maxlength="6" value="${e(pre)}" placeholder="קוד בן 6 ספרות"><button class="btn" id="join">הצטרפות</button></div></section>`);document.getElementById('back').onclick=home;document.getElementById('join').onclick=joinRoom;if(pre)setTimeout(()=>document.getElementById('join').click(),250)}
async function joinRoom(){try{const code=document.getElementById('code').value.trim();state.room=await api('GET',null,`?code=${encodeURIComponent(code)}&voterId=${encodeURIComponent(voterId)}`);state.screen='studentRoom';state.message='';render();startPolling()}catch{setMessage('לא נמצא מרחב עם הקוד הזה. בדוק את הקוד ונסה שוב.')}}
function studentStage(){const r=state.room;if(!r.stageOpen)return `<div class="notice">התחנה עדיין סגורה. המורה יפתח אותה כשתגיע העת.</div>${studentResults()}`;if(r.activeStage===1)return studentCloud();if(r.activeStage===2)return studentIdentity();return studentLab()}
function studentResults(){const r=state.room;if(!r.resultsVisible||!r.summary)return'';if(r.activeStage===1)return teacherCloud(r.summary);if(r.activeStage===2)return teacherIdentity(r.summary);return teacherLab(r.summary)}
function renderStudentRoom(){const r=state.room;app.innerHTML=shell(`<section class="panel"><div class="row space"><div><div class="muted">קוד כיתה ${e(r.code)}</div><h2>${r.activeStage}. ${e(stageNames[r.activeStage])}</h2></div><span class="chip">${r.stageOpen?'פתוח':'ממתינים למורה'}</span></div>${message()}${studentStage()}</section>`);bindStudent()}
function studentCloud(){const prev=state.room.myResponse?.words||[];return `<div><p>כתוב עד שלוש מילים קצרות שמשלימות עבורך את המשפט:</p><h2>„ישראלי.ת זה...”</h2><div class="word-form"><input class="input" id="words" value="${e(prev.join(', '))}" placeholder="לדוגמה: שייכות, עברית, משפחה"><button class="btn" id="submit">שלח</button></div>${state.room.myResponse?'<div class="notice ok">התשובה שלך נקלטה ✓ אפשר לעדכן אותה כל עוד התחנה פתוחה.</div>':''}${studentResults()}</div>`}
function studentIdentity(){const vals=state.room.myResponse?.values||{};const keys=state.room.identityKeys||[];return `<p>עד כמה כל מרכיב הוא חלק מהזהות הישראלית שלך? 1 = מעט, 5 = מאוד.</p><div class="identity-grid">${keys.map(k=>`<div class="identity-item"><label>${identityIcons[k]||'•'} ${e(k)} · <span id="v-${e(k)}">${vals[k]||3}</span></label><input class="range" data-key="${e(k)}" type="range" min="1" max="5" value="${vals[k]||3}"></div>`).join('')}</div><div class="row" style="margin-top:16px"><button class="btn" id="submit">שמור את המפה שלי</button></div>${state.room.myResponse?'<div class="notice ok">המפה שלך נשמרה ✓</div>':''}${studentResults()}`}
function studentLab(){const answers=state.room.myResponse?.answers||{};return `<p>אין כאן תשובה אחת נכונה. בחר בכל מקרה עד כמה הדמות נתפסת בעיניך כישראלית.</p><div class="lab-grid">${(state.room.labCases||[]).map(c=>`<div class="lab-card"><h3>${e(c.title)}</h3><div class="vote-options">${c.options.map((o,i)=>`<button class="vote ${Number(answers[c.id])===i?'selected':''}" data-case="${e(c.id)}" data-option="${i}">${e(o)}</button>`).join('')}</div></div>`).join('')}</div><div class="row" style="margin-top:16px"><button class="btn" id="submit">שלח את הבחירות שלי</button></div>${state.room.myResponse?'<div class="notice ok">הבחירות שלך נקלטו ✓</div>':''}${studentResults()}`}
function bindStudent(){document.querySelectorAll('.range').forEach(r=>r.oninput=()=>{const s=document.getElementById(`v-${r.dataset.key}`);if(s)s.textContent=r.value});document.querySelectorAll('.vote').forEach(v=>v.onclick=()=>{document.querySelectorAll(`.vote[data-case="${v.dataset.case}"]`).forEach(x=>x.classList.remove('selected'));v.classList.add('selected')});const btn=document.getElementById('submit');if(btn)btn.onclick=submitStudent}
async function submitStudent(){try{const r=state.room;let payload={action:'submit',code:r.code,voterId};if(r.activeStage===1){payload.words=document.getElementById('words').value.split(/[,\n]/).map(x=>x.trim()).filter(Boolean)}else if(r.activeStage===2){payload.values={};document.querySelectorAll('.range').forEach(x=>payload.values[x.dataset.key]=Number(x.value))}else{payload.answers={};document.querySelectorAll('.vote.selected').forEach(x=>payload.answers[x.dataset.case]=Number(x.dataset.option));if(Object.keys(payload.answers).length!==(r.labCases||[]).length){setMessage('יש לבחור תשובה בכל אחד מהמקרים.');return}}await api('POST',payload);await refreshRoom();state.message='';render()}catch(err){setMessage(err.message==='stage_closed'?'המורה כבר סגר את התחנה.':'לא הצלחתי לשמור את התשובה. נסה שוב.')}}

async function refreshRoom(){if(!state.room)return;try{const q=state.screen==='teacherRoom'?`?code=${state.room.code}&teacherToken=${encodeURIComponent(state.teacherToken)}`:`?code=${state.room.code}&voterId=${encodeURIComponent(voterId)}`;state.room=await api('GET',null,q)}catch{}}
let timer=null;function startPolling(){clearInterval(timer);timer=setInterval(async()=>{if(!['teacherRoom','studentRoom'].includes(state.screen))return;const before=state.room?.version;const beforeStage=state.room?.activeStage;await refreshRoom();if(state.room?.version!==before||state.room?.activeStage!==beforeStage||state.screen==='teacherRoom')render()},2500)}
function render(){if(state.screen==='home')renderHome();else if(state.screen==='teacherHome')renderTeacherHome();else if(state.screen==='teacherRoom')renderTeacherRoom();else if(state.screen==='studentJoin')renderStudentJoin();else renderStudentRoom()}
render();
