const app=document.getElementById('app');
const qs=new URLSearchParams(location.search);
const initialRole=qs.get('role');
const savedTeacher=JSON.parse(localStorage.getItem('yisraeliTeacher')||'null');
const voterId=localStorage.getItem('yisraeliVoterId')||crypto.randomUUID();
localStorage.setItem('yisraeliVoterId',voterId);
let state={screen:initialRole==='student'?'studentJoin':'home',room:null,teacherToken:savedTeacher?.teacherToken||'',message:''};
const stageNames={1:'ענן הזהות',2:'מפת הזהות הכיתתית',3:'מה הופך לישראלי?'};
const stageSub={1:'ישראלי.ת זה...',2:'מרכיבי הזהות שלנו',3:'מעבדת זהות'};
const identityIcons={'יהדות':'✡','עברית':'א','מקום':'⌖','משפחה':'♡','קהילה':'◌','תרבות':'♫','זיכרון':'◫','עתיד':'→'};
function e(s=''){return String(s).replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
async function api(method,body,query=''){const res=await fetch('/api/room'+query,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const data=await res.json().catch(()=>({}));if(!res.ok){const er=new Error(data.error||'request_failed');er.code=data.error;throw er}return data}
function shell(content){return `<main class="wrap"><section class="hero"><div class="eyebrow">תוכנית השכלה כללית · שכבה י׳</div><h1>אני ישראלי</h1><p>זהות, שייכות והסיפור שאנחנו בוחרים לספר על עצמנו.</p><div class="hero-question">מה הופך אדם לישראלי?</div></section>${content}<div class="footer">© 2026 ענת ברון־לוביש, אתי נייברג ונטלי בן חמו. כל הזכויות שמורות. אין להעתיק, להפיץ, לפרסם, לשנות או לעשות בתכנים שימוש מסחרי ללא אישור מראש ובכתב מבעלות הזכויות.</div></main>`}
function msg(){return state.message?`<div class="notice">${e(state.message)}</div>`:''}
function setMessage(t=''){state.message=t;render()}
function home(){clearInterval(timer);state={...state,screen:'home',room:null,message:''};render()}
function guide(n,t,d){return `<div class="teacher-guide"><div class="num">${n}</div><div><strong>${e(t)}</strong><p>${e(d)}</p></div></div>`}
function renderHome(){
 const recent=savedTeacher?.code?true:false;
 app.innerHTML=shell(`<div class="access-intro"><div><strong>שיעור אחד · שלוש תחנות · קוד כיתה אחד</strong><span>פותחים כיתה פעם אחת ומתקדמים בין הפעילויות לפי קצב השיעור.</span></div><div class="access-saved-badge">מרחב כיתתי חי</div></div>
 <div class="grid two access-grid">
  <section class="card access-card"><div class="access-icon">＋</div><h2>כיתה חדשה</h2><p class="muted">צרו מרחב חדש. התלמידים יקבלו קוד כיתה ו־QR אחד שילוו אותם בכל שלוש התחנות.</p><div class="field"><label for="className">שם הכיתה — לא חובה</label><input class="input" id="className" maxlength="60" placeholder="לדוגמה: י׳2"></div>${msg()}<button class="btn pri access-main-btn" id="create">יצירת כיתה חדשה</button></section>
  <section class="card access-card"><div class="access-icon">↩</div><h2>המשך כיתה קיימת</h2><p class="muted">חזרו למרחב האחרון במכשיר הזה והמשיכו בדיוק מהתחנה שבה עצרתם.</p>${recent?`<div class="saved-room"><div><span>הכיתה האחרונה</span><strong>${e(savedTeacher.code)}</strong></div><button class="btn teal access-main-btn" id="resume">פתיחת הכיתה האחרונה</button></div>`:`<div class="empty-state">עדיין לא נשמרה כיתה במכשיר זה.</div>`}<div class="access-divider"><span>לתלמידים</span></div><button class="btn ghost access-main-btn" id="studentJoin">כניסה עם קוד כיתה</button></section>
 </div>
 <section class="card lesson-roadmap"><div><strong>מהלך השיעור</strong><span>כל התחנות נמצאות באותו מסך מורה.</span></div><div class="roadmap-items">${guide(1,'ענן הזהות','ישראלי.ת זה... — מילים ראשונות שעולות בכיתה.')}${guide(2,'מפת הזהות הכיתתית','מגלים אילו מרכיבי זהות חזקים יותר בכיתה.')}${guide(3,'מה הופך לישראלי?','בוחנים דמויות ומקרים ומגלים היכן עובר הגבול.')}</div></section>`);
 document.getElementById('create').onclick=createRoom;
 if(document.getElementById('resume'))document.getElementById('resume').onclick=()=>resumeTeacher(savedTeacher);
 document.getElementById('studentJoin').onclick=()=>{state.screen='studentJoin';render()};
}
async function createRoom(){const b=document.getElementById('create');b.disabled=true;b.textContent='יוצר כיתה…';try{const data=await api('POST',{action:'create',className:(document.getElementById('className').value||'').trim()});state.room=data;state.teacherToken=data.teacherToken;state.screen='teacherRoom';localStorage.setItem('yisraeliTeacher',JSON.stringify({code:data.code,teacherToken:data.teacherToken}));render();startPolling()}catch{state.message='לא הצלחתי ליצור מרחב חדש. נסה שוב.';render()}}
async function resumeTeacher(saved){try{const data=await api('GET',null,`?code=${encodeURIComponent(saved.code)}&teacherToken=${encodeURIComponent(saved.teacherToken)}`);state.room=data;state.teacherToken=saved.teacherToken;state.screen='teacherRoom';render();startPolling()}catch{localStorage.removeItem('yisraeliTeacher');state.message='המרחב הקודם כבר אינו זמין.';render()}}
function stageStrip(active){return `<div class="stage-strip">${[1,2,3].map(n=>`<button class="stage ${active===n?'on':''}" data-stage="${n}"><b>${n}. ${e(stageNames[n])}</b><small>${e(stageSub[n])}</small></button>`).join('')}</div>`}
function shareBlock(link,code){return `<h3>כניסת תלמידים</h3><p class="muted">אותו QR ואותו קוד מלווים את הכיתה בכל שלוש התחנות.</p><div class="share"><div class="qr"><img alt="QR לכניסת תלמידים" src="/api/qr?text=${encodeURIComponent(link)}"></div><div><div class="share-link">${e(link)}</div><div class="btns"><button class="btn ghost" id="copyLink">העתקת קישור</button></div><p class="tiny">אפשר גם להיכנס עם קוד הכיתה: <strong>${e(code)}</strong></p></div></div>`}
function teacherStageContent(){const r=state.room;if(r.activeStage===1)return teacherCloud(r.summary);if(r.activeStage===2)return teacherIdentity(r.summary);return teacherLab(r.summary)}
function teacherControls(r){return `<div class="statusline"><span class="dot ${r.stageOpen?'open':'closed'}"></span><strong>${r.stageOpen?'התחנה פתוחה לתלמידים':'התחנה סגורה לתלמידים'}</strong></div><div class="btns"><button class="btn ${r.stageOpen?'danger':'teal'}" id="toggle">${r.stageOpen?'סגירת התחנה':'פתיחת התחנה'}</button><button class="btn ghost" id="visibility">${r.resultsVisible?'הסתרת התוצאות':'חשיפת התוצאות'}</button><button class="btn ghost" id="resetStage">איפוס תשובות התחנה</button></div>`}
function renderTeacherRoom(){const r=state.room;if(!r)return renderHome();const joinUrl=`${location.origin}/?role=student&code=${encodeURIComponent(r.code)}`;app.innerHTML=shell(`<section class="card teacher-header"><div class="room-head"><div><div class="eyebrow">מסך מורה${r.className?' · '+e(r.className):''}</div><h2>${e(stageNames[r.activeStage])}</h2><div class="muted">${e(stageSub[r.activeStage])}</div></div><div><div class="tiny">קוד כיתה</div><div class="room-code">${e(r.code)}</div></div></div><div class="teacher-save-note"><span>✓</span><div><strong>הכיתה נשמרת במכשיר זה</strong><small>אפשר לחזור אליה מדף הבית ולהמשיך מאותה תחנה.</small></div><button class="btn ghost" id="backHome">דף הבית</button></div>${stageStrip(r.activeStage)}</section><div class="grid two teacher-grid"><section class="card activity-card">${teacherControls(r)}${teacherStageContent()}</section><section class="card share-card">${shareBlock(joinUrl,r.code)}<div class="danger-zone"><button class="btn ghost" id="resetAll">איפוס כל השיעור</button></div></section></div>`);
 document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>teacherAction('setStage',{stage:Number(b.dataset.stage)}));
 document.getElementById('toggle').onclick=()=>teacherAction('setOpen',{open:!r.stageOpen});document.getElementById('visibility').onclick=()=>teacherAction('setVisibility',{visible:!r.resultsVisible});document.getElementById('resetStage').onclick=()=>teacherAction('resetStage');document.getElementById('resetAll').onclick=()=>{if(confirm('לאפס את כל שלוש התחנות?'))teacherAction('resetAll')};document.getElementById('backHome').onclick=home;document.getElementById('copyLink').onclick=async()=>{try{await navigator.clipboard.writeText(joinUrl);document.getElementById('copyLink').textContent='הקישור הועתק ✓'}catch{}};
}
async function teacherAction(action,extra={}){try{state.room=await api('POST',{action,code:state.room.code,teacherToken:state.teacherToken,...extra});render()}catch{setMessage('הפעולה לא בוצעה.')}}
function teacherCloud(summary={}){const words=summary?.words||{};const max=Math.max(1,...Object.values(words));const cloud=Object.entries(words).sort((a,b)=>b[1]-a[1]).map(([w,n])=>`<span class="word" style="font-size:${22+Math.round(36*n/max)}px">${e(w)}</span>`).join('');return `<div class="activity-content"><div class="row space"><div><div class="eyebrow dark">תחנה 1</div><h2>ישראלי.ת זה...</h2></div><span class="chip">${summary?.total||0} משתתפים</span></div><p class="muted">התלמידים שולחים עד שלוש מילים. הענן מתעדכן בזמן אמת.</p><div class="cloud">${cloud||'<span class="muted">המילים יופיעו כאן בזמן אמת</span>'}</div></div>`}
function teacherIdentity(summary={}){const avg=summary?.averages||{};return `<div class="activity-content"><div class="row space"><div><div class="eyebrow dark">תחנה 2</div><h2>מפת הזהות הכיתתית</h2></div><span class="chip">${summary?.total||0} משתתפים</span></div><p class="muted">ממוצע כיתתי לכל אחד ממרכיבי הזהות.</p><div class="identity-grid">${Object.entries(avg).map(([k,v])=>`<div class="identity-item"><label>${identityIcons[k]||'•'} ${e(k)}</label><div class="identity-score">${v||'–'}</div><div class="bar"><span style="width:${(v||0)*20}%"></span></div></div>`).join('')||'<p class="muted">התוצאות יופיעו כאן</p>'}</div></div>`}
function teacherLab(summary={}){return `<div class="activity-content"><div class="row space"><div><div class="eyebrow dark">תחנה 3</div><h2>מה הופך לישראלי?</h2></div><span class="chip">${summary?.total||0} משתתפים</span></div><p class="muted">השוו בין הבחירות של הכיתה בכל אחד מהמקרים.</p><div class="lab-grid">${(summary?.cases||[]).map(c=>{const total=c.counts.reduce((a,b)=>a+b,0)||1;return `<div class="lab-card"><h3>${e(c.title)}</h3>${c.options.map((o,i)=>`<div class="result-line"><div class="row space"><span>${e(o)}</span><b>${c.counts[i]||0}</b></div><div class="bar"><span style="width:${((c.counts[i]||0)/total)*100}%"></span></div></div>`).join('')}</div>`}).join('')}</div></div>`}
function renderStudentJoin(){const pre=qs.get('code')||'';app.innerHTML=shell(`<section class="card student-join"><div class="row space"><div><div class="eyebrow dark">כניסת תלמידים</div><h2>הצטרפות לשיעור</h2><p class="muted">הכנס את קוד הכיתה שמופיע אצל המורה.</p></div><button class="btn ghost" id="back">חזרה</button></div>${msg()}<div class="join"><input class="input access-code" id="code" inputmode="numeric" maxlength="6" value="${e(pre)}" placeholder="קוד בן 6 ספרות"><button class="btn pri" id="join">הצטרפות</button></div></section>`);document.getElementById('back').onclick=home;document.getElementById('join').onclick=joinRoom;if(pre)setTimeout(()=>document.getElementById('join').click(),250)}
async function joinRoom(){try{const code=document.getElementById('code').value.trim();state.room=await api('GET',null,`?code=${encodeURIComponent(code)}&voterId=${encodeURIComponent(voterId)}`);state.screen='studentRoom';state.message='';render();startPolling()}catch{setMessage('לא נמצא מרחב עם הקוד הזה. בדוק את הקוד ונסה שוב.')}}
function studentResults(){const r=state.room;if(!r.resultsVisible||!r.summary)return'';if(r.activeStage===1)return teacherCloud(r.summary);if(r.activeStage===2)return teacherIdentity(r.summary);return teacherLab(r.summary)}
function studentStage(){const r=state.room;if(!r.stageOpen)return `<div class="notice">התחנה עדיין סגורה. המורה יפתח אותה כשתגיע העת.</div>${studentResults()}`;if(r.activeStage===1)return studentCloud();if(r.activeStage===2)return studentIdentity();return studentLab()}
function renderStudentRoom(){const r=state.room;app.innerHTML=shell(`<section class="card student-room"><div class="row space"><div><div class="eyebrow dark">קוד כיתה ${e(r.code)}</div><h2>${r.activeStage}. ${e(stageNames[r.activeStage])}</h2></div><span class="chip">${r.stageOpen?'פתוח':'ממתינים למורה'}</span></div>${msg()}${studentStage()}</section>`);bindStudent()}
function studentCloud(){const prev=state.room.myResponse?.words||[];return `<div><p>כתוב עד שלוש מילים קצרות שמשלימות עבורך את המשפט:</p><h2>„ישראלי.ת זה...”</h2><div class="word-form"><input class="input" id="words" value="${e(prev.join(', '))}" placeholder="לדוגמה: שייכות, עברית, משפחה"><button class="btn pri" id="submit">שלח</button></div>${state.room.myResponse?'<div class="notice ok">התשובה שלך נקלטה ✓ אפשר לעדכן אותה כל עוד התחנה פתוחה.</div>':''}${studentResults()}</div>`}
function studentIdentity(){const vals=state.room.myResponse?.values||{};const keys=state.room.identityKeys||[];return `<p>עד כמה כל מרכיב הוא חלק מהזהות הישראלית שלך? 1 = מעט, 5 = מאוד.</p><div class="identity-grid">${keys.map(k=>`<div class="identity-item"><label>${identityIcons[k]||'•'} ${e(k)} · <span id="v-${e(k)}">${vals[k]||3}</span></label><input class="range" data-key="${e(k)}" type="range" min="1" max="5" value="${vals[k]||3}"></div>`).join('')}</div><div class="btns"><button class="btn pri" id="submit">שמור את המפה שלי</button></div>${state.room.myResponse?'<div class="notice ok">המפה שלך נשמרה ✓</div>':''}${studentResults()}`}
function studentLab(){const answers=state.room.myResponse?.answers||{};return `<p>אין כאן תשובה אחת נכונה. בחר בכל מקרה עד כמה הדמות נתפסת בעיניך כישראלית.</p><div class="lab-grid">${(state.room.labCases||[]).map(c=>`<div class="lab-card"><h3>${e(c.title)}</h3><div class="vote-options">${c.options.map((o,i)=>`<button class="vote ${Number(answers[c.id])===i?'selected':''}" data-case="${e(c.id)}" data-option="${i}">${e(o)}</button>`).join('')}</div></div>`).join('')}</div><div class="btns"><button class="btn pri" id="submit">שלח את הבחירות שלי</button></div>${state.room.myResponse?'<div class="notice ok">הבחירות שלך נקלטו ✓</div>':''}${studentResults()}`}
function bindStudent(){document.querySelectorAll('.range').forEach(r=>r.oninput=()=>{const s=document.getElementById(`v-${r.dataset.key}`);if(s)s.textContent=r.value});document.querySelectorAll('.vote').forEach(v=>v.onclick=()=>{document.querySelectorAll(`.vote[data-case="${v.dataset.case}"]`).forEach(x=>x.classList.remove('selected'));v.classList.add('selected')});const btn=document.getElementById('submit');if(btn)btn.onclick=submitStudent}
async function submitStudent(){try{const r=state.room;let payload={action:'submit',code:r.code,voterId};if(r.activeStage===1){payload.words=document.getElementById('words').value.split(/[,\n]/).map(x=>x.trim()).filter(Boolean)}else if(r.activeStage===2){payload.values={};document.querySelectorAll('.range').forEach(x=>payload.values[x.dataset.key]=Number(x.value))}else{payload.answers={};document.querySelectorAll('.vote.selected').forEach(x=>payload.answers[x.dataset.case]=Number(x.dataset.option));if(Object.keys(payload.answers).length!==(r.labCases||[]).length){setMessage('יש לבחור תשובה בכל אחד מהמקרים.');return}}await api('POST',payload);await refreshRoom();state.message='';render()}catch(err){setMessage(err.code==='stage_closed'?'המורה כבר סגר את התחנה.':'לא הצלחתי לשמור את התשובה. נסה שוב.')}}
async function refreshRoom(){if(!state.room)return;try{const q=state.screen==='teacherRoom'?`?code=${state.room.code}&teacherToken=${encodeURIComponent(state.teacherToken)}`:`?code=${state.room.code}&voterId=${encodeURIComponent(voterId)}`;state.room=await api('GET',null,q)}catch{}}
let timer=null;function startPolling(){clearInterval(timer);timer=setInterval(async()=>{if(!['teacherRoom','studentRoom'].includes(state.screen))return;const before=state.room?.version;await refreshRoom();if(state.room?.version!==before||state.screen==='teacherRoom')render()},1800)}
function render(){if(state.screen==='home')renderHome();else if(state.screen==='teacherRoom')renderTeacherRoom();else if(state.screen==='studentJoin')renderStudentJoin();else renderStudentRoom()}
render();
