(function(){
'use strict';
const params=new URLSearchParams(location.search);
const projector=params.get('projector')==='1';
const PROD='https://yisraeli-identity-live.vercel.app';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function saved(){try{return JSON.parse(localStorage.getItem('yisraeliTeacher')||'null')||{}}catch{return{}}}
function injectButton(){if(projector||document.getElementById('projectorLaunch'))return;const header=document.querySelector('.teacher-header');if(!header)return;const strip=header.querySelector('.stage-strip');if(!strip)return;const roomCode=(header.querySelector('.room-code')?.textContent||'').replace(/\D/g,'').slice(0,6);const s=saved();const token=s.teacherToken||'';if(!roomCode||!token)return;const row=document.createElement('div');row.className='projector-launch-row';row.innerHTML='<button id="projectorLaunch" class="projector-launch" type="button">▣ מצב הקרנה לכיתה</button>';strip.after(row);row.querySelector('button').onclick=()=>window.open(PROD+'/?projector=1&code='+encodeURIComponent(roomCode)+'&token='+encodeURIComponent(token),'_blank','noopener');}
if(!projector){new MutationObserver(injectButton).observe(document.getElementById('app')||document.body,{childList:true,subtree:true});injectButton();return;}
const code=(params.get('code')||'').replace(/\D/g,'').slice(0,6);const token=params.get('token')||saved().teacherToken||'';
document.body.classList.add('projector-mode');const root=document.createElement('main');root.id='projectorRoot';document.body.appendChild(root);
async function room(){const r=await fetch('/api/room?code='+encodeURIComponent(code)+'&teacherToken='+encodeURIComponent(token),{cache:'no-store'});if(!r.ok)throw new Error('room');return r.json();}
function head(r,title,sub){return '<div class="projector-head"><div><div class="projector-kicker">זהות ישראלית – זהות מורכבת'+(r.className?' · '+esc(r.className):'')+'</div><h1>'+esc(title)+'</h1><div class="projector-sub">'+esc(sub)+'</div></div><div class="projector-room"><small>תחנה פעילה</small><strong>'+r.activeStage+' / 3</strong></div></div>';}
function cloud(r){const s=r.summary||{total:0,words:{}};if(!r.resultsVisible)return wait(s.total,'תלמידים כבר שלחו מילים','הענן ייחשף על ידי המורה');const entries=Object.entries(s.words||{}).sort((a,b)=>b[1]-a[1]);const max=Math.max(1,...entries.map(x=>x[1]));return '<div class="projector-cloud">'+(entries.length?entries.map(([w,n],i)=>'<span class="c'+(i%4)+'" style="font-size:'+(38+Math.round(68*n/max))+'px">'+esc(w)+'</span>').join(''):'<div class="projector-empty">המילים יופיעו כאן בזמן אמת</div>')+'</div><div class="projector-total">'+s.total+' משתתפים</div>';}
function identity(r){const s=r.summary||{total:0,averages:{}};if(!r.resultsVisible)return wait(s.total,'תלמידים כבר מיפו את הזהות שלהם','התוצאות ייחשפו על ידי המורה');const avg=s.averages||{};return '<div class="projector-bars">'+Object.entries(avg).map(([k,v])=>'<div class="projector-bar"><div class="projector-bar-label"><b>'+esc(k)+'</b><strong>'+Number(v||0).toFixed(1)+'</strong></div><div class="projector-track"><div style="width:'+((Number(v)||0)*20)+'%"></div></div></div>').join('')+'</div><div class="projector-total">'+s.total+' משתתפים</div>';}
function lab(r){const s=r.summary||{total:0,cases:[]};if(!r.resultsVisible)return wait(s.total,'תלמידים כבר בחרו','התוצאות ייחשפו על ידי המורה');return '<div class="projector-cases">'+(s.cases||[]).map(c=>{const total=(c.counts||[]).reduce((a,b)=>a+b,0)||1;return '<section><h2>'+esc(c.title)+'</h2>'+c.options.map((o,i)=>{const n=c.counts[i]||0,p=Math.round(n*100/total);return '<div class="case-line"><div><span>'+esc(o)+'</span><strong>'+p+'%</strong></div><div class="projector-track"><div style="width:'+p+'%"></div></div></div>';}).join('')+'</section>';}).join('')+'</div><div class="projector-total">'+s.total+' משתתפים</div>';}
function wait(n,text,sub){return '<div class="projector-wait"><strong>'+n+'</strong><span>'+esc(text)+'</span><small>'+esc(sub)+'</small></div>';}
function content(r){if(r.activeStage===1)return cloud(r);if(r.activeStage===2)return identity(r);return lab(r);}
function meta(r){if(r.activeStage===1)return['ענן הזהות','ישראלי.ת זה...'];if(r.activeStage===2)return['מפת הזהות הכיתתית','מרכיבי הזהות שלנו'];return['מה הופך אדם לישראלי?','מעבדת הזהות'];}
let last='';async function tick(){try{const r=await room();const m=meta(r);const html='<div class="projector-shell">'+head(r,m[0],m[1])+'<div class="projector-toolbar"><span class="projector-status '+(r.stageOpen?'open':'')+'">'+(r.stageOpen?'הפעילות פתוחה לתלמידים':'הפעילות סגורה')+'</span><span>'+r.summary?.total+' משתתפים</span></div><div class="projector-stage">'+content(r)+'</div></div>';if(html!==last){root.innerHTML=html;last=html;}}catch(e){root.innerHTML='<div class="projector-shell"><div class="projector-wait"><span>לא ניתן לטעון את מצב ההקרנה</span><small>פתחו אותו מחדש ממסך המורה.</small></div></div>';}}tick();setInterval(tick,1200);
})();